name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start SSH agent and add key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan git.raphix.fr >> ~/.ssh/known_hosts

      - name: Deploy Subsonics as gitlab-ci
        run: |
          ssh -A -o StrictHostKeyChecking=no raphix@alpha.raphix.fr << 'EOF'
            echo "[Subsonics-Deploy] - Connexion SSH : Success"
            # Passe en gitlab-ci
            sudo -E -u gitlab-ci bash << 'INNER_EOF'
              set -e
              echo "[Subsonics-Deploy] - Stage - Déploiement  - START "
              echo "[Subsonics-Deploy] - Arrêt de Subsonics : Processing"
              cd /home/gitlab-ci
              whoami
              pm2 stop "Subsonics" || true
              pm2 delete "Subsonics" || true
              echo "[Subsonics-Deploy] - Arrêt de Subsonics : Success"

              mv /home/gitlab-ci/chopin/data/ /home/gitlab-ci/tempdata || true

              echo "[Subsonics-Deploy] - Suppression de Subsonics : Processing"
              rm -rf ./chopin
              echo "[Subsonics-Deploy] - Suppression de Subsonics : Success"

              echo "[Subsonics-Deploy] - Installation de Subsonics : Processing"
              git clone git@git.raphix.fr:subsonics/chopin.git
              echo "[Subsonics-Deploy] - Installation de Subsonics : Success"

              echo "[Subsonics-Deploy] - Installation des dépendances : Processing"
              cd /home/gitlab-ci/chopin
              rm -r /home/gitlab-ci/chopin/data || true
              mv /home/gitlab-ci/tempdata/ /home/gitlab-ci/chopin/data || true
              npm install --omit=dev
              echo "[Subsonics-Deploy] - Installation des dépendances : Success"

              echo "[Subsonics-Deploy] - Démarrage de Subsonics : Processing"
              cd /home/gitlab-ci
              pm2 start subsonic.config.js
              echo "[Subsonics-Deploy] - Démarrage de Subsonics : Success"
              echo "[Subsonics-Deploy] - Stage - Déploiement  - END"
            INNER_EOF
          EOF
